enum RadioMessage {
    message1 = 49434,
    boss = 8741
}
namespace SpriteKind {
    export const sporawn = SpriteKind.create()
    export const ser2 = SpriteKind.create()
    export const BOS = SpriteKind.create()
    export const spern = SpriteKind.create()
    export const $ = SpriteKind.create()
    export const pet = SpriteKind.create()
    export const ree = SpriteKind.create()
}
scene.onOverlapTile(SpriteKind.Player, myTiles.tile2, function (sprite, location) {
    game.over(false, effects.blizzard)
})
controller.up.onEvent(ControllerButtonEvent.Pressed, function () {
    if (rat.vy == 0) {
        rat.vy = -160
    }
})
controller.B.onEvent(ControllerButtonEvent.Pressed, function () {
    projectile = sprites.createProjectileFromSprite(img`
        . . . . . . . . . . . . . . . . 
        . . c c . . c c . . . . . . . . 
        . . c 3 c c 3 c c c . . . . . . 
        . c b 3 b c 3 b c c c . . . . . 
        . c b b b b b b b b f f . . . . 
        c c b b b b b b b b f f . . . . 
        c b 1 b b b 1 b b c f f f . . . 
        c b b b b b b b b f f f f . . . 
        f b c b b b c b c c b b b . . . 
        f b 1 f f f 1 b f c c c c . . . 
        . f b b b b b b f b b c c . . . 
        c c f b b b b b c c b b c . . . 
        c c c f f f f f f c c b b c . . 
        . c c c . . . . . . c c c c c . 
        . . c c c . . . . . . . c c c c 
        . . . . . . . . . . . . . . . . 
        `, rat, 100, -79)
    animation.runImageAnimation(
    projectile,
    [img`
        . . f f f . . . . . . . . f f f 
        . f f c c . . . . . . f c b b c 
        f f c c . . . . . . f c b b c . 
        f c f c . . . . . . f b c c c . 
        f f f c c . c c . f c b b c c . 
        f f c 3 c c 3 c c f b c b b c . 
        f f b 3 b c 3 b c f b c c b c . 
        . c b b b b b b c b b c c c . . 
        . c 1 b b b 1 b b c c c c . . . 
        c b b b b b b b b b c c . . . . 
        c b c b b b c b b b b f . . . . 
        f b 1 f f f 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        . f b b b b b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . c c . . c c . . . . . . . . 
        . . c 3 c c 3 c c c . . . . . . 
        . c b 3 b c 3 b c c c . . . . . 
        . c b b b b b b b b f f . . . . 
        c c b b b b b b b b f f . . . . 
        c b 1 b b b 1 b b c f f f . . . 
        c b b b b b b b b f f f f . . . 
        f b c b b b c b c c b b b . . . 
        f b 1 f f f 1 b f c c c c . . . 
        . f b b b b b b f b b c c . . . 
        c c f b b b b b c c b b c . . . 
        c c c f f f f f f c c b b c . . 
        . c c c . . . . . . c c c c c . 
        . . c c c . . . . . . . c c c c 
        . . . . . . . . . . . . . . . . 
        `,img`
        . f f f . . . . . . . . f f f . 
        f f c . . . . . . . f c b b c . 
        f c c . . . . . . f c b b c . . 
        c f . . . . . . . f b c c c . . 
        c f f . . . . . f f b b c c . . 
        f f f c c . c c f b c b b c . . 
        f f f c c c c c f b c c b c . . 
        . f c 3 c c 3 b c b c c c . . . 
        . c b 3 b c 3 b b c c c c . . . 
        c c b b b b b b b b c c . . . . 
        c b 1 b b b 1 b b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        f b c b b b c b b b b f . . . . 
        . f 1 f f f 1 b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `,img`
        . . f f f . . . . . . . . f f f 
        . f f c c . . . . . . f c b b c 
        f f c c . . . . . . f c b b c . 
        f c f c . . . . . . f b c c c . 
        f f f c c . c c . f c b b c c . 
        f f c 3 c c 3 c c f b c b b c . 
        f f b 3 b c 3 b c f b c c b c . 
        . c 1 b b b 1 b c b b c c c . . 
        . c 1 b b b 1 b b c c c c . . . 
        c b b b b b b b b b c c . . . . 
        c b 1 f f 1 c b b b b f . . . . 
        f f 1 f f 1 f b b b b f c . . . 
        f f 2 2 2 2 f b b b b f c c . . 
        . f 2 2 2 2 b b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . c c . c c . . . . . . . . 
        . . f 3 c c 3 c c c . . . . . . 
        . f c 3 b c 3 b c c c . . . . . 
        f c b b b b b b b b f f . . . . 
        c c 1 b b b 1 b b b f f . . . . 
        c b b b b b b b b c f f f . . . 
        c b 1 f f 1 c b b f f f f . . . 
        f f 1 f f 1 f b c c b b b . . . 
        f f f f f f f b f c c c c . . . 
        f f 2 2 2 2 f b f b b c c c . . 
        . f 2 2 2 2 2 b c c b b c . . . 
        . . f 2 2 2 b f f c c b b c . . 
        . . . f f f f f f f c c c c c . 
        . . . . . . . . . . . . c c c c 
        `,img`
        . f f f . . . . . . . . f f f . 
        f f c . . . . . . . f c b b c . 
        f c c . . . . . . f c b b c . . 
        c f . . . . . . . f b c c c . . 
        c f f . . . . . f f b b c c . . 
        f f f c c . c c f b c b b c . . 
        f f f c c c c c f b c c b c . . 
        . f c 3 c c 3 b c b c c c . . . 
        . c b 3 b c 3 b b c c c c . . . 
        c c b b b b b b b b c c . . . . 
        c 1 1 b b b 1 1 b b b f c . . . 
        f b b b b b b b b b b f c c . . 
        f b c b b b c b b b b f . . . . 
        . f 1 f f f 1 b b b c f . . . . 
        . . f b b b b b b c f . . . . . 
        . . . f f f f f f f . . . . . . 
        `],
    50,
    true
    )
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.BOS, function (sprite, otherSprite) {
    info.changeLifeBy(-2)
    animation.runImageAnimation(
    reaper,
    [img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ..a...fd111ddddddf......
        .aca..fd1dddddddbf......
        aceca.fd1dabddbbff......
        .ace..fbdd2cdbbcf.......
        ..a.effffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcfffffff.......
        ....fdfdf.ffffffff......
        .....f.f...ffffffff.....
        ............ffffffff....
        .............ffffffff...
        ..............ffffffff..
        ...............ffffffff.
        ................ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ..a...fd111ddddddf......
        .aca..fd1dddddddbf......
        aceca.fd1dabddbbff......
        .ace..fbdd2cdbbcf.......
        ..a.effffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcfffffff.......
        ....fdfdf.ffffffff......
        .....f.f...ffffffff.....
        ............ffffffff....
        .............ffffffff...
        ..............ffffffff..
        ...............ffffffff.
        ................ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ..a...fd111ddddddf......
        .aca..fd1dddddddbf......
        aceca.fd1dabddbbff......
        .ace..fbdd2cdbbcf.......
        ..a.effffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcfffffff.......
        ....fdfdf.ffffffff......
        .....f.f...ffffffff.....
        ............ffffffff....
        .............ffffffff...
        ..............ffffffff..
        ...............ffffffff.
        ................ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ..a...fd111ddddddf......
        .aca..fd1dddddddbf......
        aceca.fd1dabddbbff......
        .ace..fbdd2cdbbcf.......
        ..a.effffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcfffffff.......
        ....fdfdf.ffffffff......
        .....f.f...ffffffff.....
        ............ffffffff....
        .............ffffffff...
        ..............ffffffff..
        ...............ffffffff.
        ................ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ..a...fd111ddddddf......
        .aca..fd1dddddddbf......
        aceca.fd1dabddbbff......
        .ace..fbdd2cdbbcf.......
        ..a.effffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcfffffff.......
        ....fdfdf.ffffffff......
        .....f.f...ffffffff.....
        ............ffffffff....
        .............ffffffff...
        ..............ffffffff..
        ...............ffffffff.
        ................ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ..a...fd111ddddddf......
        .aca..fd1dddddddbf......
        aceca.fd1dabddbbff......
        .ace..fbdd2cdbbcf.......
        ..a.effffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcfffffff.......
        ....fdfdf.ffffffff......
        .....f.f...ffffffff.....
        ............ffffffff....
        .............ffffffff...
        ..............ffffffff..
        ...............ffffffff.
        ................ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ..a...fd111ddddddf......
        .aca..fd1dddddddbf......
        aceca.fd1dabddbbff......
        .ace..fbddacdbbcf.......
        ..a.effffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcfffffff.......
        ....fdfdf.ffffffff......
        .....f.f...ffffffff.....
        ............ffffffff....
        .............ffffffff...
        ..............ffffffff..
        ...............ffffffff.
        ................ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd111ddddddf......
        ......fd1dddddddbf......
        ......fd1dabddbbff......
        ......fbddacdbbcf.......
        .....fbddccddbfff.......
        .....fefffbfcffff.......
        ...a.ef..ffffffff.......
        ..ace.....ffffffff......
        .aceca.....ffffffff.....
        ..aca.......ffffffff....
        1..a..1......ffffffff...
        .1...1........ffffffff..
        ..1.1..........ffffffff.
        ...1............ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd111ddddddf......
        ......fd1dddddddbf......
        ......fd1dabddbbff......
        ......fbddacdbbcf.......
        .....fbddccddbfff.......
        .....fefffbfcffff.......
        ...a.ef..ffffffff.......
        ..ace.....ffffffff......
        .aceca.....ffffffff.....
        ..aca.......ffffffff....
        1..a..1......ffffffff...
        .1...1........ffffffff..
        ..1.1..........ffffffff.
        ...1............ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd111ddddddf......
        ......fd1dddddddbf......
        ......fd1dabddbbff......
        ......fbddacdbbcf.......
        .....fbddccddbfff.......
        .....fefffbfcffff.......
        ...a.ef..ffffffff.......
        ..ace.....ffffffff......
        .aceca.....ffffffff.....
        ..aca.......ffffffff....
        1..a..1......ffffffff...
        .1...1........ffffffff..
        ..1.1..........ffffffff.
        ...1............ffffffff
        `,img`
        ........................
        ....f...................
        ....ff..................
        ...f11f..fffff..........
        ...fd11fffaf11ff........
        ....fd111faaf11bf.......
        .....fd111faaf1dbf......
        ......fd111ff11ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd111ddddddf......
        ......fd1dddddddbf......
        ......fd1dabddbbff......
        ......fbddacdbbcf.......
        .....fbddccddbfff.......
        .....fefffbfcffff.......
        ...a.ef..ffffffff.......
        ..ace.....ffffffff......
        .aceca.....ffffffff.....
        ..aca.......ffffffff....
        1..a..1......ffffffff...
        .1...1........ffffffff..
        ..1.1..........ffffffff.
        ...1............ffffffff
        `],
    1,
    false
    )
    pause(1000)
})
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    if (rat.vy == 0) {
        rat.vy = -160
    }
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.spern, function (sprite, otherSprite) {
    ararararrarr13zyd3fxerztxdv23ygrxbcru3y4.destroy()
    mySprite2 = sprites.create(img`
        ..................ffffffffffff.....................................................................fffff............
        ..................ffffffffffffff..................................................................ffffff............
        ..................fffffffffffffffff...............................................................ffffff............
        .....................ffffffffffffffff............................................................fffffff............
        .........................fffffffffffffff.........................................................fffffff............
        ..........................ffffffffffffffff......................................................fffffff.............
        ............................fffffffffffffffff...................................................fffffff.............
        ...............................ffffffffffffffff................................................fffffff..............
        .................................ffffffffffffffff..............................................fffffff..............
        ....................................ffffffffffffffff..........................................fffffff...............
        ......................................ffffffffffffff..........................................fffffff...............
        .........................................fffffffffff.........................................fffffff................
        ...........................................fffffffff........................................ffffffff................
        .................................fffffffffffffffffffffffff.........ffffffffffffffffffffffff.fffffff.................
        ................................ffffffffffffffffffffffffffffff....fffffffffffffffffffffffffffffffff.................
        ...............................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..................
        ..............................fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...................
        ........fffffffffffff........ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff...................
        ........ffffffffffffffff..fffffffffffffffffffffffffffffaaaaafffffffffff................fffffffff....................
        ........fffffffffffffffffffffffffaaaaaffffffffaaaaaffffaaaaaffffffffff..............................................
        ........ffffffffffffffffffffffffcccaaaffffffffcccaaffffacccaffffffffff..............................................
        ........ffffffffffffffffffffffffcccaaaffffffffcccaaffffacccaffffffffff..............................................
        ...........fffffffffffffffffffffcccaaaffffffffcccaaffffacccaffffffffff..............................................
        ........fffffffffffffffffffffffffaaaaaffffffffaaaaafffffffffffffffffff..............................................
        .....fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..............................................
        .....ffffffffffffffffffffffffffffffffffffffffffffffffffcccaaffffffffff..............................................
        .....ffffffffffffff......fffffffffffffffffffffaacccffffcccaafffffffffff.............................................
        .....fffffffffff........ffffffffffffffffffffffaacccffffcccaafffffffffffff...........................................
        .....fffffff............fffffffffaaaaaffffffffaacccffffaaaaafffffffffffffff.........................................
        ......................fffffffffffacccaffffffffaaaaaffffaaaaaffffffffffffffff........................................
        .....................ffffffffffffacccaffffffffaaaaafffffffffffffffffffffffffff......................................
        fffff...............fffffffffffffacccafffffffffffffffffffffffffffffffffffffffff.....................................
        fffffff.............fffffffffffffaaaaafffffffffffffffffffffffffffffffffffffffff.....................................
        ffffffffffffff......fffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.....................................
        fffffffffffffff.....ffffffffffffffffffffffffffaaaaaffffaaaaafffffffffffffffffff.....................................
        fffffffffffffffff...ffffffffffffffffffffffffffaaaaaffffaaaaafffffffffffffffffff.....................................
        fffffffffffffffff...fffffffffffffaaaaaffffffffacccaffffcccaafffffffffffffffffff.....................................
        ..ffffffffffffffff..fffffffffffffacccaffffffffacccaffffcccaafffffffffffffffffff.....................................
        ..........fffffffff.fffffffffffffacccaffffffffacccaffffcccaafffffffffffffffffff.....................................
        ...........ffffffffffffffffffffffacccafffffffffffffffffffffffffffffffffffffffff.....................................
        ............fffffffffffffffffffffaaaaafffffffffffffffffffffffffffffffffffffffff.....................................
        .............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.....................................
        ..............fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.....................................
        ...............ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.....................................
        ................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff......................................
        ........fffffff...ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff......................................
        ........ffffffffff.....ffffffffffffffffffffffffffffffffffffffffffffffffffffff.......................................
        ........ffffffffffff...fffffffffffffffffffffffffffffffffffffffffffffffffffff........................................
        ........ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff........................................
        ........fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.........................................
        ...........ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff.........................................
        .............fffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..........................................
        ................ffffffffffffffffffffffffffffffffffffffffffffffffffffffffff..........................................
        .......................fffffffffffffffffffffffffffffffffffffffffffffffffff..........................................
        ......................ffffffffffffffffffffffffffffffffffffffffffffffffffff..........................................
        .....................ffffffffffffffffffffffffffffffffffffffffffffffffffff...........................................
        .....................ffffffffffffffffffffffffffffffffffffffffffffffffffff...........................................
        .....................fffffffffffffffffffffffffffffffffffffffffffffffffffff..........................................
        ....................ffffffffffffffffffffffffffffffffffffffffffffffffffffff..........................................
        ....................fffffffffffffffffff.ffffffffffffffffffffffffffffffffff..........................................
        ...................fffffffffffffffffff.ffffffff..fffffffffffffffffffffffff..........................................
        ...................fffffffffffffffff...fffffff.....fffffffffffffffff.fffff..........................................
        ..................fffffffffffffffff...fffffff.........fffffffff......fffff..........................................
        ..................fffffff.ffffffff...ffffffff..........ffffffff......fffff..........................................
        .................fffffff..fffffff....fffffff............ffffffff.....fffff..........................................
        .................fffffff..ffffff....ffffffff.............fffffff.....fffff..........................................
        .................ffffff.............fffffff..............ffffffff....fffff..........................................
        .................ffffff............fffffff................fffffff....fffff..........................................
        .................fffff............ffffffff.................fffffff..ffffff..........................................
        ................ffffff............fffffff..................fffffff..ffffff..........................................
        ................ffffff...........ffffffff...................fffffff.ffffff..........................................
        ...............fffffff...........fffffff....................ffffffffffffff..........................................
        ...............fffffff..........fffffff......................ffffffffffff...........................................
        ...............ffffff..........ffffffff......................ffffffffffff...........................................
        ...............ffffff..........fffffff........................fffffffffff...........................................
        ...fffff.......fffff..........ffffffff........................ffffffffff............................................
        ...ffffff......fffff.........ffffffff..........................ffffffff.............................................
        ...ffffffff....fffff........ffffffff..........................ffffffff..............................................
        ...ffffffffff..fffff........ffffffff.........................ffffffff...............................................
        ...fffffffffff.fffff.......ffffffff.........................ffffffff................................................
        ...fffffffffffffffff.....fffffffffffffff....................ffffffff................................................
        ....ffffffffffffffff.....ffffffffffffffffff................fffffffff................................................
        ......ffffffffffffff....ffffffffffffffffffff..............ffffffffff................................................
        .........fffffffffff...fffffffff.fffffffffffff...........fffffffffff................................................
        ..........ffffffffff...ffffffff..ffffffffffffffff......fffffffffffff................................................
        .............fffffff.fffffffff......fffffffffffffff...ffffffffffffff................................................
        .....................ffffffff..........fffffffffffffffffffffffffffff................................................
        .....................fffffff............ffffffffffffffffffffffffffff................................................
        ....................ffffffff.............fffffffffffffffffffffffffff................................................
        ...ffffffffffff....ffffffff..................ffffffffffffff.fffffff.................................................
        ...fffffffffffffffffffffff.....................fffffffffff.ffffffff.................................................
        ...fffffffffffffffffffffff.................................fffffff..................................................
        ...ffffffffffffffffffffff.................................fffffff...................................................
        ...fffffffffffffffffffff..................................fffffff...................................................
        ...........ffffffffffff..................................fffffff....................................................
        .............fffffffff...................................fffffff....................................................
        ........................................................fffffff.....................................................
        ..................................................fffffffffffff.....................................................
        ..................................................ffffffffffff......................................................
        ..................................................ffffffffffff......................................................
        ..................................................fffffffffff.......................................................
        ..................................................ffffffffff........................................................
        ..................................................ffffffffff........................................................
        ....................................................fffffff.........................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        ....................................................................................................................
        `, SpriteKind.$)
})
statusbars.onStatusReached(StatusBarKind.Health, statusbars.StatusComparison.LTE, statusbars.ComparisonType.Percentage, 50, function (status) {
    reaper.follow(rat, 200)
    projectile2 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . 2 a . . . . . . . . 
        . . . . . . a a a . . . . . . . 
        . . . . . . . a a a . . . . . . 
        . . . . . . . . a a a . . . . . 
        . . . . . . . . . a . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.ree)
    projectile2.follow(rat, 250)
})
statusbars.onZero(StatusBarKind.EnemyHealth, function (status) {
    game.over(true)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Food, function (sprite, otherSprite) {
    info.changeScoreBy(1)
    otherSprite.destroy()
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.BOS, function (sprite, otherSprite) {
    statusbar.value += -1
})
scene.onOverlapTile(SpriteKind.Player, myTiles.tile10, function (sprite, location) {
    game.over(true, effects.bubbles)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.ser2, function (sprite, otherSprite) {
    radio.sendMessage(RadioMessage.boss)
    reaper = sprites.create(img`
        ..............................
        ..............................
        ..............................
        ..............................
        ...........f..................
        ..........f1f.................
        ..........f11f..ffff..........
        ..........fd11fff111ff........
        ...........fd11faff11bf.......
        ............fd11faaf1dbf......
        ............fd11faaf1ddf......
        ............fd111fffdddf......
        ...2222.....fd111ddddddf......
        ..2fffe.....fd111ddddddf......
        .2f2222e....fd1dddddddbf......
        2f2.....e...fd1dabddbbff......
        22.......e..fbddacdbbcf.......
        ..........effffccddbccf.......
        ..........fcb1bbbcccccf.......
        ..........f1b1dcffffffff......
        ..........fdfdfffffffffff.....
        ...........f.f..ffffffffff....
        .................ffffffffff...
        ..................ffffffffff..
        ...................ffffffffff.
        ....................ffffffffff
        .....................fffffffff
        ..............................
        ..............................
        ..............................
        `, SpriteKind.BOS)
    spawner_20.destroy()
    reaper.follow(rat, 99)
    statusbar = statusbars.create(20, 4, StatusBarKind.EnemyHealth)
    statusbar.value = 100
    statusbar.setStatusBarFlag(StatusBarFlag.SmoothTransition, true)
})
sprites.onOverlap(SpriteKind.Projectile, SpriteKind.Enemy, function (sprite, otherSprite) {
    mon.destroy(effects.smiles, 5000)
    info.changeScoreBy(1)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.ree, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    pause(100)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.sporawn, function (sprite, otherSprite) {
    otherSprite.destroy(effects.fire, 500)
    mon = sprites.create(img`
        ........................
        ...1....................
        1..11...................
        11..11....ffff..........
        .11..11.ff1111ff........
        ..11..11b111111bf.......
        ..111..11111111dbf......
        ....111d1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd111ddddddf......
        ......fd1dddddddbf......
        ......fd1dfbddbbff......
        ......fbddfcdbbcf.......
        .....ffffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcffffffff......
        ....fdfdf..ffffffffff...
        .....f.f.....ffffff.....
        ........................
        ........................
        ........................
        ........................
        ........................
        `, SpriteKind.Enemy)
    animation.runImageAnimation(
    mon,
    [img`
        ........................
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111df.......
        ......fd1111111ddf......
        ......fd111111dddf......
        f.....fd111ddddddf......
        ff....fd1dabddddbf......
        fff...fbddacdbbbcf......
        fff....f11111bbcf.......
        ffff...f1b1fffff........
        ffff...fbfc111bf........
        fffff...ff1b1bff........
        .fffffffffbfbfff.f......
        .fffffffffffffffff......
        ..fffffff...fffff.......
        ...fffff................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        ..........fffff.........
        ........ff1111bff.......
        .......fb1111111bf......
        .......f111111111f...f..
        ......fd1111111ffff...f.
        ......fd111dd1c111bf..ff
        ......fb11fcdf1b1bff..f.
        ......f11111bfbfbff...ff
        ......f1b1bdfcffff.f..f.
        ......fbfbfcfcccf...f.f.
        ......ffffffffff.....ff.
        .........ffffff.........
        .........ffffff.........
        .........fffffff..f.....
        ..........fffffffff.....
        ...........fffffff......
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ..........ffff..........
        ........ff1111ff........
        .......fb111111bf.......
        .......f1111111dbf......
        ......fd1111111ddf......
        ......fd111111dddf......
        ......fd111ddddddf......
        ......fd111ddddddf......
        ......fd1dddddddbf......
        ......fd1dfbddbbff......
        ......fbddfcdbbcf.......
        .....ffffccddbfff.......
        ....fcb1bbbfcffff.......
        ....f1b1dcffffffff......
        ....fdfdf..ffffffffff...
        .....f.f.....ffffff.....
        ffff....................
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        .........fffff..........
        ........f11111ff........
        .......fb111111bf.......
        .......f1111111dbf......
        ......fd111111dddf......
        ......fd11111ddddf......
        f.....fd11dddddddf......
        ff....f111dddddddf......
        .ff...f11fcddddddf......
        .ff..fb1111bdddbf.......
        ..ff.f1b1bdfcfff........
        ...fffbfbffffffff.......
        ....fffffffffffff.ff....
        ...........ffffffff.....
        ........f1b1bffffff.....
        ........fbfbffffff......
        ........................
        ........................
        ........................
        ........................
        `,img`
        ........................
        ........................
        ........................
        ........................
        .........fffff..........
        ........f11111ff........
        .......fb111111bf.......
        ..a....f1111111dbf......
        .a....fd111111dddf......
        ....a.fd11111ddddf......
        a..a..fd11dddddddf......
        aa...af111dddddddf......
        .aa.a.f11fcddddddf......
        .aa..fb1111bdddbf.......
        ..aa.f1b1bdfcfff........
        ...aafbfbffffffff.......
        ....affffffffffff.ff....
        ...........ffffffff.....
        ........f1b1bffffff.....
        ........fbfbffffff......
        ........................
        ........................
        ........................
        ........................
        `],
    0,
    true
    )
    mon.setPosition(rat.x + 80, rat.y - 80)
    mon.follow(rat)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    info.changeLifeBy(-1)
    mon.destroy(effects.halo, 500)
})
let mon: Sprite = null
let statusbar: StatusBarSprite = null
let projectile2: Sprite = null
let mySprite2: Sprite = null
let reaper: Sprite = null
let projectile: Sprite = null
let ararararrarr13zyd3fxerztxdv23ygrxbcru3y4: Sprite = null
let spawner_20: Sprite = null
let spawner: Sprite = null
let fooooood: Sprite = null
let rat: Sprite = null
scene.setBackgroundImage(img`
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccccccccccfcccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccccccfccccccccc
    cccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccccccccccccfccccccccc
    ccccccccccccccccccccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccccccccfcccccccccc
    cccccaccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccccccccccccccfcccccccccc
    ccccccaccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccccfccccccccccc
    cccccccaccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccacccccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccc
    ccccccccaaccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccaacccccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccc
    ccccccccccaccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccacccccccccccccccccacccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccc
    cccccccccccacccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccaacccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccc
    ccccccccccccacccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccaccccccccccaacccccccccccccccccccccccccccccccccccccccccccccccccccccfccccccccccccc
    cccccccccccccacccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccaacccccccaccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccccc
    ccccccccccccccaacccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccaccccaacccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccccccccccccc
    ccccccccccccccccacccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccaacaccccccccccccccccccccccccccccccccccccccccccccccccccccccccfacccccccccccccc
    cccccccccccccccccaccccccccccccccccccccccccccccccccaccccccccccccfcccccccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccccccccccccccfcccaccccccccccc
    ccccccccccccccccccaccccccccccccccccccccccccccccccccacccccccccccfccccccccccccccccccccaccaccccccccccccccccccccccccccccccccccccccccccccccccccccccaafcaacccccccccccc
    cccccccccccccccccccaccccccccccccccccccccccccccccccccaacccccccccfccccccccccccccccccaaccccaacccccccccccccccccccccccccccccccccccccccccccccccccccabfaacccccccccccccc
    ccccccccccccccccccccacccccccccccccccacccccccccccccccccacccccccccfcccccccccccccccaaccccccccacccccccccccccccccccccccccccccccccccccccccccccccccabafcccccccccccccccc
    cccccccccccccccccccccaacccccccccccccaccccccccccccccccccaacccccccfccccccccccccccacccccccccccaacccccccccccccccccccccccccccccccccccccccccccccaaaafccccccccccccccccc
    cccccccccccccccccccccccacccccfcccccccacccccccccccccccccccacccccccfcccccccccccaaccccccccccccccacccccccccccccccccccccccccccccccccccccccccccaaaccfccccccccccccccccc
    ccccccccccccccccccccccccacccccfccccccaccccccccccccccccccccaccccccfccccccccccacccccccccccccccccaaccccccccccccccccccccccccccccccccccccccccaacccfcccccccccccccccccc
    cccccccccccccccccccccccccacccccfccccccaccccccccccccccccccccaaccccfccccccccaaccccccccccccccccccccaccccccccccccccccccccccccccccccccccccccacccccfcccccccccccccccccc
    ccccccccccccccccccccccccccacccccfccccccacccccccccccccccccccccaccccfcccccaacccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccaacccccfccccccccccccccccccc
    cccccccccccccccccccccccccccaaccccfcccccaccccccccccccccccccccccaaccfccccacccccccccccccccccccccccccccaccccccccccccccccccccccccccccfccaacccccccfccccccccccccccccccc
    cccccccccccccccccccccccccccccaccccfcccccacccccccccccccccccccccccaccfcaacccccccccccccccccccccccccccccaacccccccccccccccccccccccccfbaaacccccccfcccccccccccccccccccc
    ccccccccccccccccccccccccccccccaccccfccccaccccccccccccccccccccccccaafacccccccccccccccccccccccccccccccccaccccccccccccccccccccccffaabaccccccccfcccccccccccccccccccc
    cccccccccccccccccccccccccccccccaccccfccccaccccccccccccccccccccccccafccccccccccccccccccfccccccccccccccccaacccccccccccccccccccfaabaaccccccccfccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccaccccfcccacccccccccccccccccccccccaccfccccccccccccccccccfcccccccccccccccccacccccccccccccccccfaccaccccccccccfccccccccccccccccccccc
    cfcccccccccccccccccccccccccccccccaccccfcccaccccccccccccccccccccaacccfaacccccccccccccccccfcccccccccccccccccaacccccccccccccffcccaccccccccccfcccccccccccccccccccccc
    ccfcccccccccccccccccccccccccccccccaacccfccaccccccccccccccccccaacccccfccaccccccccccccccccfcccccccccccccccccccacccccccccccfaccaacccccccccccfcccccccccccccccccccccc
    cccffcccccccccccccccccccccccccccccccacccfccaccccccccccccccccaccccccccfccaacccccccccccccccfcccccccccccccccccccaacccccccafcccaccccccccccccfccccccccccccccccccccccc
    cccccfcccccccccccccccccccccccccccccccacccfccacccccccccccccaacccccccccfccccacccccccccccccccfccccccccccccccccccccaccccaafcccacccccccccccccfccccccccccccccccccccccc
    ccccccfcccccccccccccccccccccccccccccccacccfcaccccccccccccaccccccccccccfccccacccccccccccccccfccccccccccccccccccccaaaaffcccacccccccccccccfcccccccccccccccccccccccc
    cccccccfcccccccccccccccccccccccccccccccacccfbacccccccccaacccccccccccccfcccccaaccccccccccccccfcccccccccccccccccccaaafcccaaccccccccccccccfcccccccccccccccccccccccc
    ccccccccffccccccccccccccccccccccccccccccaaccfacccccccaacccccccccccccccfcccccccaccccccccccccccfccccccccccccccccaabbfaccacccccccccccccccfccccccccccccccccccccccccc
    ccccccccccfcccccccccccccccccccccccccccccccaccfacccccaccccccccccccccccccfcccccccaaccccccccccccfcccccccccccccccabbffbbaaccccccccccccccccfccccccccccccccccccccccccc
    cccccccccccfcccccccccccccccccccccccccccccccaccfcccaacccccccccccccccccccfcccccccccaccccccccccccfccccccccccccaabbfbbbbabaccccccccccccccfcccccccccccccccccccccccccc
    ccccccccccccfcccccccccccccccccccccccccccccccaccfcaccccccccccccccccccccccfcccccccccaccccccccccccfcccccccccaabbbfbbbaabbbaacccccccaaaaafaaaaaaaaaaaaaaaaaacccccccc
    cccccccccccccfcccccccccccccccccccccccccccccccacafcccccccccccccccccccccccfccccccccaaaaaaaaaaaaaaafaaaaaaaaaaaffaaaaaaaaaaaaaaaaaaccccfccccccccccccccccccccccccccc
    ccccccccccccccffcccccccccccccccccaaaaaaaaaaaaaaaafaaaaaaaaaaaaaaaaaaaaaafaaaaaaaaccccacccccccccccfbbbaaccccfccccacccccccccaaccccccccfccccccccccccccccccccccccccc
    cccccccccaaaaaaafaaaaaaaaaaaaaaaacccccccccccacccaafccccccccccccccccccccccfccccccccccccaaccccccccccfaacccccfcccaaccccccccccccacccccccfccccccccccccccccccccccccccc
    cccccccccccccccccfccccccccccccccccccccccccaacccccabfcccccccccccccccccccccfccccccccccccccaccccccccafccccccfcccacccccccccccccccaaccccfcccccccccccccccccccccccccccc
    ccccccccccccccccccfccccccccccccccccccccccaccccccccabfcccccccccccccccccccccfccccccccccccccaccccccaccfcccffcccaccccccccccccccccccacccfcccccccccccccccccccccccccccc
    cccccccccccccccccccffccccccccccccccccccaacccccccccaabfccccccccccccccccccccfcccccccccccccccaaccaaccccfcfccccaccccccccccccccccccccaafccccccccccccccccccccccccccccc
    cccccccccccccccccccccfccccccccccccccccaccccccccccccaabfcccccccccccccccccccfcccccccccccccccccaacccccccfcccaacccccccccccccccccccccccfccccccccccccccccccccccccccccc
    ccccccccccccccccccccccfcccccccccccccaacccccccccccccabaafcccccccccccccccccccfccccccccccccccaacaaccccffbfcaccccccccccccccccccccccccfcaaccccccccccccccccccccccccccc
    ccaccccccccccccccccccccfccccccccccaaccccccccccccccccaccafccccccccccccccccccfccccccccccccaacccccaccfbbbbfcccccccccccccccccccccccccfcccacccccccccccccccccccccccccc
    cccaccccccccccccccccccccffcccccccacccccccccccccccccccaccafcccccccccccccccccfccccccccccaaccccccccafbbbaafccccccccccccccccccccccccfcccccaacccccccccccccccccccccccc
    ccccaaccccccccccccccccccccfccccaaccccccccccccccccccccacccafcccccccccccccccccfcccccccaaccccccccccfaabacccfcccccccccccccccccccccccfcccccccaccccccccccccccccccccccc
    ccccccaccccccccccccccccccccfccacccccccccccccccccccccccacccafccccccccccccccccfccccccaccccccccccffcccacccccfcccccccccccccccccccccfcccccccccaaccccccccccccccccccccc
    cccccccaccccccccccccccccccccfaccccccccccccccccccccccccaccccafccccccccccccccccfcccaaccccccccccfccccacaaccccfccccccccccccccccccccfcccccccccccacccccccccccccccccccc
    ccccccccaaccccccccccccccccaacfcccccccccccccccccccccccccaccccfacccccccccccccccfcaacccccccccccfcccaaccccaccccfccccccccccccccccccfcccccccccccccaacccccccccccccccccc
    ccccccccccaccccccccccccccaccccffcccccccccccccccccccccccacccccfaccccccccccccccfacccccccccccffcccacccccccaccccfcccccccccccccccccfcccccccccccccccaccccccccccccccccc
    cccccccccccacccccccccccaacccccccfcccccccccccccccccccccccacccccfacccccccccccaacfccccccccccfccccacccccccccaacccfcccccccccccccccfcccccccccccccccccacccccccccccccccc
    ccccccccccccacccccccccaccccccccccfccccccccccccccccccccccaccccccfaccccccccaacccfcccccccccfccccaccccccccccccaccfcccccccccccccccfccccccccccccccaaccaacccccccccccccc
    cccccccccccccaacccccccccccccccccccfccccccccccccccccccccccaccccccfaccccccaccccccfccccccffcccaaccccccccccccccaabfcccccccccccccfcccccccccccccaaccccccaccccccccccccc
    cccccccccccccccacccccccccccccccccccffcccccccccccccccccccccaccccccfaaccaacccccccfcccccfccccaccccccccccccccccccabfccccccccccccfccccccccccaaacccccccccaaccccccccccc
    ccccccccccccccccaccccccccccccccccccccfccccccccccccccccccccacccccccfbaacccccccccfccccfccccaccccccccccccccccccccabfccccccccccfcccccccccaaccccccccccccccacccccccccc
    cccccccccccccccccaacccccccccccccccccccfccccccccccccccccccccaccccccafbaccccccccccfccfcccaaccccccccccccccccccccccaafcccccccccfcccccccaacccccccccccccccccaacccccccc
    cccccccccccccccccccacccccccccccccccccccfcccccccccccccccccccaccccaaccfbacccccccccfffcccaccccccccccccccccccccccccccafcccccccfcccccaaacccccccccccccccccccccaccccccc
    ccccccccccccccccccccacccccccccccccccccccffccccccccccccccccccacaacccccfbaccccccccfccccaccccccccccccccccccccccccccccfaccccccfcccaacccccccccccccccccccccccccaaccccc
    cccccccccccccccccccccaccccccccccccccccccccfcccccccccccccccccaaccccccccfbaacccccfcfccaccccccccccccccccccccccccccccccfaccccfbaaacccccccccccccccccccccccccccccacccc
    ccccccccccccccccccccccaacccccccccccccccccccfcccccccccccccccacacccccccccfbbaccffccfaaccccccccccccccccccccccccccccccccfacccfacccccccccccccccccccccccccccccccccaacc
    ccccccccccccccccccccccccacccccccccccccccccccfccccccccccccaaccaccccccccccfbbafccccafccccccccccccccccccccccccccccccccccfaafcccccccccccccccccccccccccccccccccccccac
    cccccccccccccccccccccccccacccccccccccccccccccffccccccccaacccccaccccccccccfbfacccacfcccccccccccccccccccccccccccccccccaafbfccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccaacccccccccccccccccccfcccccaaccccccccaccccccccccfbbaaaccfcccccccccccccccccccccccccccccccaacccffaaccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccacccccccccccccccccccfccaaccccccccccaccccccccffcfbaaccccfcccccccccccccccccccccccccccaaacccccfcccacccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccacccccccccccccccccccfacccccccccccccaccccccfccccfccaaccfcccccccccccccccccccccccccaaccccccccffcccaccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccaccccccccccccccccaacfcccccccccccccacccccfccccacfcccaccfccccccccccccccccccccccaacccccccccfccfcccaaccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccaacccccccccccccaccccffccccccccccccaccffcccaacccfcccacfcccccccccccccccccccaaacccccccccccfcccfccccacccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccaccccccccccaacccccccfcccccccccccacfccccaccccccfcccafcccccccccccccccccaacccccccccccccfcccccfccccaacccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccacccccccaaccccccccccfcccccccccccfccccaccccccccfcccafcccccccccccccaaacccccccccccccccfccccccfcccccaccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccaacccaacccccccccccccfccccccccffcaccaccccccccccfcccfaccccccccccaacccccccccccccccccfcccccccfccccccaaccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccaaaccccccccccccccccffcccccfcccaaaccccccccccccfcccfacccccccaacccccccccccccccccccfccccccccfcccccccacccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccaaacccccccccccccccccccfcccfccccaaccccccccccccccfccfbacccaaaccccccccccccccccccccfccccccccccfcccccccaccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccaacccacccccccccccccccccccfcfccccacacccccccccccccccfcfbbaaacccccccccccccccccccccccfcccccccccccfcccccccaaccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccaccccccaacccccccccccccccccffcccaacccacccccccccccccccfbfaaacccccccccccccccccccccccfcccccccccccccfccccccccacccccccccccccccccccccc
    cccccccccccccccccccccccccccccccaacccccccccacccccccccccccccfccccacccccacccccccccccccccaffcccaccccccccccccccccccccccfccccccccccccccfccccccccaacccccccccccccccccccc
    cccccccccccccccccccccccccccccaaccccccccccccacccccccccccccfccccacccccccaccccccccccccaaccfccccaacccccccccccccccccccfcccccccccccccccfccccccccccaccccccccccccccccccc
    cccccccccccccccccccccccccccaacccccccccccccccaccccccccccffccccaccccccccacccccccccaaacccccfcccccaccccccccccccccccccfccccccccccccccccfccccccccccacccccccccccccccccc
    cccccccccccccccccccccccccaaccccccccccccccccccaacccccccfccccaaccccccccccaccccccaaccccccccffcccccaccccccccccccccccfccccccccccccccccccfccccccccccaacccccccccccccccc
    cccccccccccccccccccccccaaccccccccccccccccccccccacccccfccccacccccccccccccaccaaacccccccccccffcccccacccccccccccccccfcccccccccccccccccccfcccccccccccaccccccccccccccc
    cccccccccccccccccccccaacccccccccccccccccccccccccacccfccccaccccccccccccccaaaccccccccccccccfcfcccccacccccccccccccfcccccccccccccccccccccccccccccccccaaccccccccccccc
    ccccccccccccccccccccaccccccccccccccccccccccccccccaffccccaccccccccccccccaaacccccccccccccccfccfcccccaacccccccccccfcccccccccccccccccccccccccccccccccccacccccccccccc
    ccccccccccccccccccaacccccccccccccccccccccccccccccfcaccaaccccccccccccaaaccaccccccccccccccccfccfccccccacccccccccfcccccccccccccccccccccccccccccccccccccaccccccccccc
    ccccccccccccccccaaccccccccccccccccccccccccccccccfcccaaccccccccccccaaccccccacccccccccccccccfccccccccccaccccccccfccccccccccccccccccccccccccccccccccccccaaccccccccc
    ccccccccccccccaaccccccccccccccccccccccccccccccffccccaacccccccccaaacccccccccccccccccccccccccfccccccccccaccccccfcccccccccccccccccccccccccccccccccccccccccacccccccc
    ccccccccccccaacccccccccccccccccccccccccccccccfccccaaccaacccccaaccccccccccccccccccccccccccccfcccccccccccacccccfccccccccccccccccccccccccccccccccccccccccccaacccccc
    ccccccccccaaccccccccccccccccccccccccccccccccfccccaccccccaccaaccccccccccccccccccccccccccccccfccccccccccccaaccfcccccccccccccccccccccccccccccccccccccccccccccaccccc
    ccccccccaaccccccccccccccccccccccccccccccccffccccacccccccaaacccccccccccccccccccccccccccccccccfcccccccccccccacfccccccccccccccccccccccccccccccccccccccccccccccacccc
    cccccccacccccccccccccccccccccccccccccccccfccccccccccccaaccaacccccccccccccccccccccccccccccccccccccccccccccccafcccccccccccccccccccccccccccccccccccccccccccccccaacc
    ccccccccccccccccccccccccccccccccccccccccfccccccccccaaaccccccaccccccccccccccccccccccccccccccccccccccccccccccfacccccccccccccccccccccccccccccccccccccccccccccccccac
    cccccccccccccccccccccccccccccccccccccccfcccccccccaaccccccccccacccccccccccccccccccccccccccccccccccccccccccccfcacccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccffccccccccaacccccccccccccacccccccccccccccccccccccccccccccccccccccccccfcccaccccccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccfcccccccaaaccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccfccccaaccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccfccccccaacccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccfcccccccacccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccffccccaaaccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccccccfccccccccaccccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccfccccaaccccccccccccccccccccccccccccaacccccccccccccccccccccccccccccccccccfccccccccccacccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccfcccaaccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccfcccccccccccaccccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccaaacccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccfcccccccccccccaaccccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccaacccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccfcccccccccccccccacccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccccccccccccccccaaccccccccccccccccccccccccccccfcccccccccccccccccaccccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccfccccccccccccccccccacccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaacccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccccccccccccccccaacccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaacccccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccacccccccccccccccccccccccccc
    ccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccaccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    cccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccccc
    `)
sprites.setDataImage(rat, "bat", sprites.builtin.forestBat4)
info.setLife(5)
let myCorg = corgio.create(SpriteKind.pet, 10, 70)
rat = sprites.create(img`
    . . . . f f f f f f . . . . . . 
    . . f f e e e e f 2 f . . . . . 
    . f f e e e e f 2 2 2 f . . . . 
    . f e e e f f e e e e f . . . . 
    . f f f f e e 2 2 2 2 e f . . . 
    . f e 2 2 2 f f f f e 2 f . . . 
    f f f f f f f e e e f f f . . . 
    f f e 4 4 e b f 4 4 e e f 6 7 7 
    f e e 4 d 4 1 f d d e f . 6 e 7 
    . f e e e 4 d d d d f . 6 e 6 6 
    . . f f e e 4 4 4 e f . e 6 . . 
    . . . 4 d d e 2 2 2 f e . . . . 
    . . . e d d e 2 2 2 f . . . . . 
    . . . f e e f 4 5 5 f . . . . . 
    . . . . f f f f f f . . . . . . 
    . . . . . f f f . . . . . . . . 
    `, SpriteKind.Player)
controller.moveSprite(rat, 100, 0)
rat.ay = 300
tiles.setTilemap(tilemap`level`)
scene.cameraFollowSprite(rat)
for (let value of tiles.getTilesByType(myTiles.tile4)) {
    fooooood = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . e e e e e . . . . . . 
        . . . . e e e e e e e e e . . . 
        . . . e e e f e f e e e e e . . 
        . . . e e e f e e e e f e e e . 
        . . . e f e e e e f e e e e e . 
        . . . e e e e f e e e e e e e . 
        . . . e e e e e e e e e e e . . 
        . . . . e e e e e e e e e . . . 
        . . . . . e e e e e . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.Food)
    animation.runImageAnimation(
    fooooood,
    [img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e e e e . . . . . 
        . . . e e e e f e e e e e . . . 
        . . . e e e f e e f e e e e . . 
        . . . e e e e e f e e f e e . . 
        . . . e e e f e e e e e e e . . 
        . . . . e e e e e f e e e e . . 
        . . . . . . e e e e e e . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e e f e . . . . . 
        . . . e e e e f e e e f e . . . 
        . . . e f e f e e f e e e e . . 
        . . . e e e e e f e e f e f . . 
        . . . e e e f e e e e e e e . . 
        . . . . e e e e f f e e f e . . 
        . . . . . . e e e e e e . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `,img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . e e e e e e e . . . . . 
        . . . e e e e f e e f e e . . . 
        . . . e e e f e e f e e e e . . 
        . . . e f e e e f e e f e e . . 
        . . . e e e f e e e e e e f . . 
        . . . . e e e e e f e e e e . . 
        . . . . . . e f e e e e . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `],
    200,
    true
    )
    tiles.placeOnRandomTile(fooooood, myTiles.tile4)
    tiles.placeOnTile(fooooood, value)
    tiles.setTileAt(value, myTiles.transparency16)
}
for (let value2 of tiles.getTilesByType(myTiles.tile5)) {
    spawner = sprites.create(img`
        . . . . . . f . f . . . . . . . 
        . . . . . f . f . f . . . . . . 
        . . . . f . f . f . f . . . . . 
        . . . f . f . f . f . f . . . . 
        . . f . f . f . f . f . f . . . 
        f f . f . f . f . f . f . f f . 
        f . f . f . f . f . f . f . f f 
        f f . f . f . f . f . f . f f . 
        . . f . f . f . f . f . f . . . 
        . . f f f f f f f f f f f . . . 
        . f f f f f f f f f f f f . . . 
        . f f f f f f f f f f f f . . . 
        . f f f f f f f f f f f f . . . 
        . f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        f f f f f f f f f f f f f f f f 
        `, SpriteKind.sporawn)
    tiles.placeOnTile(spawner, value2)
    tiles.setTileAt(value2, myTiles.transparency16)
}
for (let value3 of tiles.getTilesByType(myTiles.tile7)) {
    spawner_20 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . f . . . . . . . . . 
        . . . . . f f f . . . . . . . . 
        . . . . f a a a f . . . . . . . 
        . . . . f a f a f . . . . . . . 
        . . . . f a a a f . . . . . . . 
        . . . . f f f f f . . . . . . . 
        . . . f f a a a f f . . . . . . 
        . . . f f a f a f f . . . . . . 
        . . f f f a a a f f f . . . . . 
        . . . f f f f f f f . . . . . . 
        . . . . . f f f . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.ser2)
    tiles.placeOnTile(spawner_20, value3)
    tiles.setTileAt(value3, myTiles.transparency16)
}
for (let value4 of tiles.getTilesByType(myTiles.tile10)) {
    ararararrarr13zyd3fxerztxdv23ygrxbcru3y4 = sprites.create(img`
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . a . . . . . . . . 
        . . . . . . a a a . . . . . . . 
        . . . . . a a a a a . . . . . . 
        . . . . . a f a f a . . . . . . 
        . . . . . a a f a a . . . . . . 
        . . . . . a f a f a . . . . . . 
        . . . . . a a a a a . . . . . . 
        . . . . . . a a a . . . . . . . 
        . . . . . . . a . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        . . . . . . . . . . . . . . . . 
        `, SpriteKind.spern)
    tiles.placeOnTile(ararararrarr13zyd3fxerztxdv23ygrxbcru3y4, value4)
    tiles.setTileAt(value4, myTiles.transparency16)
}
